---
ocean:
  version: "1"
snapshots:
  - name: jupyter
    registry: docker_hub
    image: jupyter/scipy-notebook
    tag: latest
steps:
  - engines:
    - name: jupyter
      dns:
        enabled: true
        default_value: 'jupyter'
        label: Jupyter URL
      settings:
        - name: mode
          label: Jupyter Mode
          style: dropdown
          default_value: 'lab'
          options:
            - value: lab
              label: 'Lab'
            - value: notebook
              label: 'Notebook'
      vars:
        - name: port
          value: "{% reserve_public_port %}"
        - name: token
          value: "{% generate_uuid %}"
      orchestrator:
        deployment_strategy: main
        snapshot_name: jupyter
        container:
          user: root
          workdir: "/home/{{ workspace.user.name }}"
          mounts:
            app_files:
              - name: jupyter_startup
                app_files_path: /
                container_path: /ocean/etc
                readonly: true
            data_stores: "{{ engines.jupyter.orchestrator.container.workdir }}"
            ssh: "/home/{{ workspace.user.name }}/.ssh"
          nodes:
            main:
              command: "{{ engines.jupyter.orchestrator.container.mounts.app_files.jupyter_startup.container_path }}/startup.sh"
              env_vars:
                - name: JUPYTER_ENABLE_LAB
                  value: "{% if engines.jupyter.settings.mode.value == 'lab' %}yes{% else %}no{% endif %}"
                - name: NB_UID
                  value: "{{ workspace.user.uid }}"
                - name: NB_GID
                  value: "{{ workspace.user.gid }}"
                - name: NB_USER
                  value: "{{ workspace.user.name }}"
                - name: NB_GROUP
                  value: "{{ workspace.user.group }}"
                - name: CHOWN_HOME
                  value: "yes"
                - name: GRANT_SUDO
                  value: "yes"
                - name: RESTARTABLE
                  value: "yes"
      ui:
        buttons:
          - node_target: main
            label: Open Jupyter
            url: "http://{{ engines.jupyter.dns.url }}:{{ engines.jupyter.vars.port }}?token={{ engines.jupyter.vars.token }}"